### ISSUE TITLE
AttributeError: module 'pidfile' has no attribute 'PIDFile'

### ISSUE THREAD

**Issue by 097115** [peterjschroeder/redp#1]
After creating and editing the configuration file, launched `redpull` and got the following error:

    redpull> ./redpull.py
    Traceback (most recent call last):
      File "./redpull.py", line 164, in main
        with pidfile.PIDFile(path_pid+"/redpull.pid"):
    AttributeError: module 'pidfile' has no attribute 'PIDFile'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "./redpull.py", line 186, in <module>
        main()
      File "./redpull.py", line 182, in main
        except pidfile.AlreadyRunningError:
    AttributeError: module 'pidfile' has no attribute 'AlreadyRunningError'

macOS, Python 3.7.4, pidfile-0.1.1, praw-7.1.0 prawcore-1.5.0 update-checker-0.18.0

EDIT: same with 3.7.9 on Ubuntu.

**Comment by peterjschroeder** [comment]
Remove pidfile and install python-pidfile.

**Comment by 097115** [comment]
@peterjschroeder That helped, thanks. But now I face another problem:

    redpull> ./redpull.py
    2020-09-15 20:46:21,430 [WARNING] Run "redpull --create" first to create a subscriptions file. Modify as needed. Than re-execute redpull.
    redpull> ./redpull.py --create
    Traceback (most recent call last):
      File "./redpull.py", line 186, in <module>
        main()
      File "./redpull.py", line 167, in main
        config_create_subscriptions()
      File "./redpull.py", line 59, in config_create_subscriptions
        for i in list(reddit.user.subreddits(limit=None)):
      File "/Users/redacted/Library/Python/3.7/lib/python/site-packages/praw/models/listing/generator.py", line 62, in __next__
        self._next_batch()
      File "/Users/redacted/Library/Python/3.7/lib/python/site-packages/praw/models/listing/generator.py", line 72, in _next_batch
        self._listing = self._reddit.get(self.url, params=self.params)
      File "/Users/redacted/Library/Python/3.7/lib/python/site-packages/praw/reddit.py", line 497, in get
        return self._objectify_request(method="GET", params=params, path=path)
      File "/Users/redacted/Library/Python/3.7/lib/python/site-packages/praw/reddit.py", line 584, in _objectify_request
        path=path,
      File "/Users/redacted/Library/Python/3.7/lib/python/site-packages/praw/reddit.py", line 765, in request
        json=json,
      File "/Users/redacted/Library/Python/3.7/lib/python/site-packages/prawcore/sessions.py", line 339, in request
        url=url,
      File "/Users/redacted/Library/Python/3.7/lib/python/site-packages/prawcore/sessions.py", line 235, in _request_with_retries
        url,
      File "/Users/redacted/Library/Python/3.7/lib/python/site-packages/prawcore/sessions.py", line 195, in _make_request
        timeout=timeout,
      File "/Users/redacted/Library/Python/3.7/lib/python/site-packages/prawcore/rate_limit.py", line 35, in call
        kwargs["headers"] = set_header_callback()
      File "/Users/redacted/Library/Python/3.7/lib/python/site-packages/prawcore/sessions.py", line 282, in _set_header_callback
        self._authorizer.refresh()
      File "/Users/redacted/Library/Python/3.7/lib/python/site-packages/prawcore/auth.py", line 356, in refresh
        password=self._password,
      File "/Users/redacted/Library/Python/3.7/lib/python/site-packages/prawcore/auth.py", line 157, in _request_token
        response, payload["error"], payload.get("error_description")
    prawcore.exceptions.OAuthException: invalid_grant error processing request

**Comment by peterjschroeder** [comment]
Is your reddit username and password in the config file?

.config/redpull/config

**Comment by 097115** [comment]
Yep. Without quotes just in case :) Something like this:

    reddit_username = MyUserName
    reddit_password = mypassword

**Comment by peterjschroeder** [comment]
I think I was wrong assuming I could share the api keys for others to use. I will fix it later and edit the instructions.

To get it working now, got to https://www.reddit.com/prefs/apps/
Create another app
Select script
Name it something
Put something in the redirect url ex:https://github.com/peterjschroeder/redpull
edit redpull.py
client_secret is the secret on that page
client_id is under personal use script on that page

EDIT: I update the script config so you can put your api keys in the config file rather than edition the script itself.

**Comment by 097115** [comment]
Aha, this works, thank you. Now, it looks like this:

    redpull> ./redpull.py
    2020-09-15 20:40:57,839 [INFO] Fetching submissions for vim.

Upon launching, it creates folder structure in `~/Mail`, but I see no messages there at all. Folders `~/Mail/Reddit/vim/{cur,new,tmp}` are just empty...

**Comment by peterjschroeder** [comment]
You're welcome. I appreciate that you are helping me uncover some bugs.

Anything in ~/.var/log/redpull.log?

EDIT: It only grabs posts from the last hour, so that may be it. Try with something like news or edit ~/.config/redpull/subscribbed and set the unix timestamp to something earlier.

**Comment by 097115** [comment]
> EDIT: It only grabs posts from the last hour, so that may be it. Try with something like news.

Oh, I see. Somehow missed that :)

Yeah, now it's working. Thanks a lot :)

**Comment by peterjschroeder** [comment]
You're welcome.

I have to update redpush to use client_id client_secret from config too, but I won't be able to until later this evening. If you are looking to test replying you can just edit the script directly until I update it.

**Comment by 097115** [comment]
OK, no problem at all :)
